[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps --force"
  NETLIFY_USE_YARN = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
